databases:

  - name: <%= ENV['USERNAME'] %>

    databaseName: time_tracker

    user: root



services:

  - type: web

    name: <%= ENV['USERNAME']%>


    env: ruby

    buildCommand: "./bin/render-build.sh"

    startCommand: "bundle exec rails server"

    plan: free

    envVars:

      - key: <%= ENV['DATABASE_URL'] %>

        fromDatabase:

          name: <%= ENV['USERNAME']%>

          property: connectionString

      - key: SECRET_KEY_BASE

        generateValue: true