# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Attendance.all.destroy_all
User.all.destroy_all
User.create(email: "admin@techcreatix.com", name: "Techcreatix", password: "Techcre@tix@786", password_confirmation: "Techcre@tix@786", role: "admin")
User.create(email: "zain@techcreatix.com", name: "Syed Zain", password: "U9B7G0QAV", password_confirmation: "U9B7G0QAV", role: "user", slack_member_id: "U9B7G0QAV")
User.create(email: "ali@techcreatix.com", name: "Ali Gillani", password: "U8XSA5J9W", password_confirmation: "U8XSA5J9W", role: "user", slack_member_id: "U8XSA5J9W")
User.create(email: "saad@techcreatix.com", name: "Saad Siddique", password: "U01EJLEV9ED", password_confirmation: "U01EJLEV9ED", role: "user", slack_member_id: "U01EJLEV9ED")
User.create(email: "ameer.hamza@techcreatix.com", name: "Ameer Hamza", password: "U01JHMQCFC3", password_confirmation: "U01JHMQCFC3", role: "user", slack_member_id: "U01JHMQCFC3")
User.create(email: "hamza.amin@techcreatix.com", name: "Hamza Amin", password: "U01Q30Y8EJH", password_confirmation: "U01Q30Y8EJH", role: "user", slack_member_id: "U01Q30Y8EJH")
User.create(email: "rajab.ali@techcreatix.com", name: "Rajab Ali", password: "U01QC88D1M2", password_confirmation: "U01QC88D1M2", role: "user", slack_member_id: "U01QC88D1M2")
User.create(email: "muhammad.sumair@techcreatix.com", name: "Muhammad Sumair", password: "U02EMABTY0H", password_confirmation: "U02EMABTY0H", role: "user", slack_member_id: "U02EMABTY0H")
User.create(email: "sohail.ahmad@techcreatix.com", name: "Sohail Ahmad", password: "U02NL9E977Z", password_confirmation: "U02NL9E977Z", role: "user", slack_member_id: "U02NL9E977Z")
User.create(email: "khizar.shoaib@techcreatix.com", name: "Khizar Shoaib Khan", password: "U02QS428LCU", password_confirmation: "U02QS428LCU", role: "user", slack_member_id: "U02QS428LCU")
User.create(email: "ayesha.rasheed@techcreatix.com", name: "Ayesha Rasheed", password: "U032361FKJB", password_confirmation: "U032361FKJB", role: "user", slack_member_id: "U032361FKJB")
User.create(email: "Usamachatta@techcreatix.com", name: "Usama Chattha", password: "U03LW43Q8V6", password_confirmation: "U03LW43Q8V6", role: "user", slack_member_id: "U03LW43Q8V6")
User.create(email: "shoaib@techcreatix.com", name: "Shoaib Nazar", password: "U03QEE8B9SP", password_confirmation: "U03QEE8B9SP", role: "user", slack_member_id: "U03QEE8B9SP")
User.create(email: "kashifali@techcreatix.com", name: "Kashif Ali", password: "U04G9TPM3JT", password_confirmation: "U04G9TPM3JT", role: "user", slack_member_id: "U04G9TPM3JT")
User.create(email: "umarmirza@techcreatix.com", name: "Umar Mirza", password: "U04GMFTSV7X", password_confirmation: "U04GMFTSV7X", role: "user", slack_member_id: "U04GMFTSV7X")
User.create(email: "Zulquairnain@techcreatix.com", name: "Zulquairnain", password: "U04MTP44TB2", password_confirmation: "U04MTP44TB2", role: "user", slack_member_id: "U04MTP44TB2")
User.create(email: "m.shahzaib@techcreatix.com", name: "Shahzaib Sohaib", password: "U04UX8PTCRZ", password_confirmation: "U04UX8PTCRZ", role: "user", slack_member_id: "U04UX8PTCRZ")
User.create(email: "manohar@techcreatix.com", name: "Manohar Rehman" , password: "U052N9G1KS7", password_confirmation: "U052N9G1KS7", role: "user", slack_member_id: "U052N9G1KS7")
User.create(email: "asim.sher@techcreatix.com", name: "Asim Sher", password: "U05720DSY3T", password_confirmation: "U05720DSY3T", role: "user", slack_member_id: "U05720DSY3T")
User.create(email: "a.ishfaq@techcreatix.com", name: "Abdullah Ishfaq", password: "U056LCRTAQM", password_confirmation: "U056LCRTAQM", role: "user", slack_member_id: "U056LCRTAQM")
User.create(email: "a.malik@techcreatix.com", name: "Abubakar Malik", password: "U056T7NR0AZ", password_confirmation: "U056T7NR0AZ", role: "user", slack_member_id: "U056T7NR0AZ")
User.create(email: "alimurtaza@techcreatix.com", name: "Ali Murtaza", password: "U05DF57K7NY", password_confirmation: "U05DF57K7NY", role: "user", slack_member_id: "U05DF57K7NY")
User.create(email: "hamzahanif@techcreatix.com", name: "Hamza Hanif", password: "U05KVG3RMUM", password_confirmation: "U05KVG3RMUM", role: "user", slack_member_id: "U05KVG3RMUM")
User.create(email: "mahnoor@techcreatix.com", name: "Mahnoor Masood", password: "U05TK7D304W", password_confirmation: "U05TK7D304W", role: "user", slack_member_id: "U05TK7D304W")
User.create(email: "ali.musa@techcreatix.com", name: "Ali Moosa", password: "U05S8Q3P3FX", password_confirmation: "U05S8Q3P3FX", role: "user", slack_member_id: "U05S8Q3P3FX")
User.create(email: "s.gilani@techcreatix.com", name: "Shahzaib Gillani", password: "U062AG3LLH5", password_confirmation: "U062AG3LLH5", role: "user", slack_member_id: "U062AG3LLH5")
User.create(email: "abdulrehman@techcreatix.com", name: "Abdur Rehman", password: "UDKLNUBDY", password_confirmation: "UDKLNUBDY", role: "user", slack_member_id: "UDKLNUBDY")
User.create(email: "saad.salman@techcreatix.com", name: "Saad Salman", password: "U068EEF6U5U", password_confirmation: "U068EEF6U5U", role: "user", slack_member_id: "U068EEF6U5U")
User.create(email: "talha.rashid@techcreatix.com", name: "Talha Rashid", password: "U068M3V16V8", password_confirmation: "U068M3V16V8", role: "user", slack_member_id: "U068M3V16V8")
User.create(email: "abdul.qayyum@techcreatix.com", name: "Abdul Qayyum", password: "U06820SNXPF", password_confirmation: "U06820SNXPF", role: "user", slack_member_id: "U06820SNXPF")
User.create(email: "eman.tahir@techcreatix.com", name: "Eman Tahir", password: "U06L1UL3F2M", password_confirmation: "U06L1UL3F2M", role: "user", slack_member_id: "U06L1UL3F2M")